name: Deploy App
on:
  push:
    branches:
      - main
      
  workflow_dispatch:
    inputs:
      title:
        description: "Title for the deployment"
        required: true
        default: "Build App"
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Instalar dependências
        run: pnpm install

      - name: Build
        run: pnpm build
